### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Yaty** [Yaty/DonkeyKong#1]
- Déplacements
  - [x] Collisions
  - [x]  Gravité Personnage
  - [x] Saut (une fois que le saut est lancé à droite on ne peut revenir en arrière)
  - [ ] Gravité Échelles
  - [ ] Décéleration gauche/droite (bonus)
- Tonneau
  - [ ] Random
  - [x] Roule
  - [x] Gravité (trou + échelles)
- Personnages
  - [x] Donkey Kong
  - [x] Princesse Peach
- Score
  - [ ] 1UP
  - [x] Score
- Bonus
  - [ ] Marteau
  - [x] Pièces
  - [ ] Saut au dessus d'un tonneau, ...
  - [ ] Animations

[ ] Carte

**Comment by Yaty** [comment]
@gdormoy @bibeul
